# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches:
    - main
    - test_ci
    - CK_dev
  pull_request:
    branches:
    - main
    - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: "3.11"

# The following command allows to connect to the ci-container via ssh
# very useful for debugging
# source: https://github.com/marketplace/actions/debugging-with-tmate

#     - name: Setup tmate session
#       uses: mxschmitt/action-tmate@v3

    - name: Install pip
      run: |
        python -m pip install uv

    - name: Installing requirements and this package
      run: |
        # install this package
        uv pip install --system -r requirements.txt
        pip install -e .

#    TODO: make this work (see __init__.py)

    - name: get test-data
      run: |
        git clone https://github.com/cknoll/atsds-demo.git

    - name: run all tests
      run: |
        python -m unittest

    - name: run some basic commands
      run: |
        cd atsds-demo
        xaiev --help
        xaiev --version
        xaiev --bootstrap

    # temporary debugging
    - name: Setup tmate session
      id: tmate
      uses: mxschmitt/action-tmate@v3
      with:
        detached: true

    - name: Capture tmate output
      run: |
          echo "Starting tmate session..."
          echo "SSH command: ${{ steps.tmate.outputs.ssh }}" > tmate-output.log
          echo "WebURL command: ${{ steps.tmate.outputs.web }}" >> tmate-output.log
          echo "tmate session ended." >> tmate-output.log

    - name: Upload tmate logs as artifact
      uses: actions/upload-artifact@v3
      with:
        name: tmate-logs
        path: tmate-output.log
